driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos66
    driver:
      box: chef
      network:
      - ["forwarded_port", {host: 8880, guest: 80}]
      - ["forwarded_port", {host: 8443, guest: 443}]
      - ["private_network", {ip: "10.10.10.40"}]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[apache::default]
    attributes:
